/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlsv.view;

import com.qlsv.controller.BangDiemController;
import com.qlsv.controller.TextBubbleBorder;
import com.qlsv.models.SinhVien;
import com.qlsv.models.User;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Hiddenpants-H
 */
public class BangDiemCaNhan extends CommonJPanel {

    /**
     * Creates new form BangDiemCaNhan
     */
    public BangDiemCaNhan(User user) {
        initComponents();
        bangDiemjTable.getTableHeader().setFont(new Font("Arial",Font.BOLD,12));
        bangDiemjTable.getTableHeader().setBackground(new Color(255,102,102));
        bangDiemjTable.getTableHeader().setForeground(new Color(255,255,255));
        tongKetjTable.getTableHeader().setFont(new Font("Arial",Font.BOLD,12));
        tongKetjTable.getTableHeader().setBackground(new Color(255,102,102));
        tongKetjTable.getTableHeader().setForeground(new Color(255,255,255));
        setController(new BangDiemController(bangDiemjTable, tongKetjTable, hocKyjTextField, maHPjTextField, tenHPjTextField, tCjTextField, maLopjTextField, qTjTextField, cKjTextField, DiemjTextField, user));
        ((BangDiemController)controller).setBangDiem();
        ((BangDiemController)controller).setTextBangDiem();
        ((BangDiemController)controller).setTextTongKet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangDiemjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tongKetjTable = new javax.swing.JTable();
        hocKyjTextField = new javax.swing.JTextField();
        maHPjTextField = new javax.swing.JTextField();
        tenHPjTextField = new javax.swing.JTextField();
        tCjTextField = new javax.swing.JTextField();
        maLopjTextField = new javax.swing.JTextField();
        qTjTextField = new javax.swing.JTextField();
        cKjTextField = new javax.swing.JTextField();
        DiemjTextField = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1272, 850));

        bangDiemjTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bangDiemjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Học kỳ", "Mã HP", "Tên HP", "TC", "Lớp học", "Điểm QT", "Điểm CK", "Điểm chữ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bangDiemjTable.setAlignmentX(1.0F);
        bangDiemjTable.setAlignmentY(1.0F);
        bangDiemjTable.setGridColor(new java.awt.Color(102, 102, 102));
        bangDiemjTable.setRowHeight(25);
        bangDiemjTable.setSelectionBackground(new java.awt.Color(102, 255, 255));
        jScrollPane1.setViewportView(bangDiemjTable);
        if (bangDiemjTable.getColumnModel().getColumnCount() > 0) {
            bangDiemjTable.getColumnModel().getColumn(0).setMinWidth(100);
            bangDiemjTable.getColumnModel().getColumn(0).setMaxWidth(100);
            bangDiemjTable.getColumnModel().getColumn(1).setMinWidth(100);
            bangDiemjTable.getColumnModel().getColumn(1).setMaxWidth(100);
            bangDiemjTable.getColumnModel().getColumn(2).setMinWidth(200);
            bangDiemjTable.getColumnModel().getColumn(2).setMaxWidth(200);
            bangDiemjTable.getColumnModel().getColumn(3).setMinWidth(100);
            bangDiemjTable.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Bảng điểm sinh viên");

        tongKetjTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tongKetjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Học Kỳ", "GPA", "CPA", "TC qua", "TC tích lũy", "Trình độ"
            }
        ));
        tongKetjTable.setRowHeight(25);
        tongKetjTable.setSelectionBackground(new java.awt.Color(102, 255, 255));
        jScrollPane2.setViewportView(tongKetjTable);

        hocKyjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        hocKyjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        hocKyjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hocKyjTextFieldKeyReleased(evt);
            }
        });

        maHPjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        maHPjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        maHPjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maHPjTextFieldKeyReleased(evt);
            }
        });

        tenHPjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tenHPjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        tenHPjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tenHPjTextFieldKeyReleased(evt);
            }
        });

        tCjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tCjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        tCjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCjTextFieldKeyReleased(evt);
            }
        });

        maLopjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        maLopjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        maLopjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maLopjTextFieldKeyReleased(evt);
            }
        });

        qTjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        qTjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        qTjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qTjTextFieldKeyReleased(evt);
            }
        });

        cKjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cKjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        cKjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cKjTextFieldKeyReleased(evt);
            }
        });

        DiemjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DiemjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        DiemjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DiemjTextFieldKeyReleased(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton9.setText("Reset");
        jButton9.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton10.setText("In bảng điểm(Excel)");
        jButton10.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(393, 393, 393)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hocKyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maHPjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tenHPjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tCjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maLopjTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qTjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cKjTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiemjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DiemjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cKjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maLopjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qTjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tCjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenHPjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maHPjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hocKyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        ((BangDiemController)controller).setBangDiem();
        ((BangDiemController)controller).setTextBangDiem();
        ((BangDiemController)controller).setTextTongKet();
        ((BangDiemController)controller).setNULL();
        
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        ((BangDiemController)controller).exportBD();
    }//GEN-LAST:event_jButton10MouseClicked

    private void hocKyjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hocKyjTextFieldKeyReleased
        ((BangDiemController)controller).hocKyFilter();
    }//GEN-LAST:event_hocKyjTextFieldKeyReleased

    private void maHPjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maHPjTextFieldKeyReleased
        // TODO add your handling code here:
        ((BangDiemController)controller).maHPFilter();
    }//GEN-LAST:event_maHPjTextFieldKeyReleased

    private void tenHPjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenHPjTextFieldKeyReleased
        // TODO add your handling code here:
        ((BangDiemController)controller).tenHPFilter();
    }//GEN-LAST:event_tenHPjTextFieldKeyReleased

    private void tCjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCjTextFieldKeyReleased
        // TODO add your handling code here:
        ((BangDiemController)controller).tcFilter();
    }//GEN-LAST:event_tCjTextFieldKeyReleased

    private void maLopjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maLopjTextFieldKeyReleased
        // TODO add your handling code here:
        ((BangDiemController)controller).maLopFilter();
    }//GEN-LAST:event_maLopjTextFieldKeyReleased

    private void qTjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qTjTextFieldKeyReleased
        // TODO add your handling code here:
        ((BangDiemController)controller).diemQTFilter();
    }//GEN-LAST:event_qTjTextFieldKeyReleased

    private void cKjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKjTextFieldKeyReleased
        // TODO add your handling code here:
        ((BangDiemController)controller).diemCKFilter();
    }//GEN-LAST:event_cKjTextFieldKeyReleased

    private void DiemjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DiemjTextFieldKeyReleased
        // TODO add your handling code here:
        ((BangDiemController)controller).diemChuFilter();
    }//GEN-LAST:event_DiemjTextFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DiemjTextField;
    private javax.swing.JTable bangDiemjTable;
    private javax.swing.JTextField cKjTextField;
    private javax.swing.JTextField hocKyjTextField;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField maHPjTextField;
    private javax.swing.JTextField maLopjTextField;
    private javax.swing.JTextField qTjTextField;
    private javax.swing.JTextField tCjTextField;
    private javax.swing.JTextField tenHPjTextField;
    private javax.swing.JTable tongKetjTable;
    // End of variables declaration//GEN-END:variables
}
