/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlsv.view;

import com.qlsv.controller.Controller;
import com.qlsv.controller.ListStudentController;
import com.qlsv.controller.TextBubbleBorder;
import com.qlsv.models.MonHoc;
import com.qlsv.models.User;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Hiddenpants-H
 */
public class ListStudentJPanel extends CommonJPanel {
    private MonHoc monHoc;

    public MonHoc getMonHoc() {
        return monHoc;
    }

    public void setMonHoc(MonHoc monHoc) {
        this.monHoc = monHoc;
    }
    
    /**
     * Creates new form ListStudentInClass
     */
    public ListStudentJPanel(User user, MonHoc monHoc) {
        initComponents();
        setMonHoc(monHoc);
        dSSVjTable.getTableHeader().setFont(new Font("Arial",Font.BOLD,12));
        dSSVjTable.getTableHeader().setBackground(new Color(255,102,102));
        dSSVjTable.getTableHeader().setForeground(new Color(255,255,255));
        setController(new ListStudentController(monHoc, dSSVjTable, sTTjTextField, maSVjTextField, tenSVjTextField, diemGKjTextField, diemCKjTextField, changeDiemGKjTextField, ChangeDiemCKjTextField, maHPjLabel, maLopjLabel, tenHPjLabel, hocKyjLabel, themSVjButton, xoaSVjButton, user));
        ((ListStudentController)controller).setTextDSSV();
        ((ListStudentController)controller).setLabel();
        ((ListStudentController)controller).setView();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dSSVjTable = new javax.swing.JTable();
        sTTjTextField = new javax.swing.JTextField();
        maSVjTextField = new javax.swing.JTextField();
        tenSVjTextField = new javax.swing.JTextField();
        diemGKjTextField = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        diemCKjTextField = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        maLopjLabel = new javax.swing.JLabel();
        maHPjLabel = new javax.swing.JLabel();
        tenHPjLabel = new javax.swing.JLabel();
        hocKyjLabel = new javax.swing.JLabel();
        changeDiemGKjTextField = new javax.swing.JTextField();
        ChangeDiemCKjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        xoaSVjButton = new javax.swing.JButton();
        themSVjButton = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1272, 850));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách sinh viên");

        dSSVjTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dSSVjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sinh viên", "Tên sinh viên", "Điểm giữa kì", "Điểm cuối kì"
            }
        ));
        dSSVjTable.setRowHeight(25);
        dSSVjTable.setSelectionBackground(new java.awt.Color(102, 255, 255));
        dSSVjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dSSVjTableMouseClicked(evt);
            }
        });
        dSSVjTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dSSVjTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(dSSVjTable);
        if (dSSVjTable.getColumnModel().getColumnCount() > 0) {
            dSSVjTable.getColumnModel().getColumn(0).setMinWidth(100);
            dSSVjTable.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        sTTjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sTTjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        sTTjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTTjTextFieldActionPerformed(evt);
            }
        });
        sTTjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sTTjTextFieldKeyReleased(evt);
            }
        });

        maSVjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        maSVjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        maSVjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSVjTextFieldActionPerformed(evt);
            }
        });
        maSVjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maSVjTextFieldKeyReleased(evt);
            }
        });

        tenSVjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tenSVjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        tenSVjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tenSVjTextFieldKeyReleased(evt);
            }
        });

        diemGKjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        diemGKjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        diemGKjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                diemGKjTextFieldKeyReleased(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setText("Trở lại");
        jButton5.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        diemCKjTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        diemCKjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        diemCKjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                diemCKjTextFieldKeyReleased(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton7.setText("Reset");
        jButton7.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        maLopjLabel.setBackground(new java.awt.Color(255, 255, 255));
        maLopjLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        maLopjLabel.setText("Mã Lớp: ");

        maHPjLabel.setBackground(new java.awt.Color(255, 255, 255));
        maHPjLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        maHPjLabel.setText("Mã học phần: ");

        tenHPjLabel.setBackground(new java.awt.Color(255, 255, 255));
        tenHPjLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tenHPjLabel.setText("Tên học phần: ");

        hocKyjLabel.setBackground(new java.awt.Color(255, 255, 255));
        hocKyjLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        hocKyjLabel.setText("học kỳ: ");

        changeDiemGKjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        changeDiemGKjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));

        ChangeDiemCKjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ChangeDiemCKjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Điểm cuối kì");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Điểm giữa kì");

        jButton8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton8.setText("Cập nhật điểm");
        jButton8.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        xoaSVjButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        xoaSVjButton.setText("Xóa Sinh viên đã chọn khỏi lớp");
        xoaSVjButton.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        xoaSVjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoaSVjButtonMouseClicked(evt);
            }
        });

        themSVjButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        themSVjButton.setText("Thêm SV(excel)");
        themSVjButton.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        themSVjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themSVjButtonMouseClicked(evt);
            }
        });
        themSVjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themSVjButtonActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton11.setText("Export file(excel)");
        jButton11.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton12.setText("Cập nhật điểm(excel)");
        jButton12.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maHPjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(maLopjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tenHPjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hocKyjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(561, 561, 561))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(373, 373, 373)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 155, Short.MAX_VALUE)))
                        .addGap(13, 13, 13)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sTTjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maSVjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tenSVjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diemGKjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diemCKjTextField))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(xoaSVjButton)
                                .addGap(35, 35, 35)
                                .addComponent(themSVjButton)
                                .addGap(18, 18, 18)
                                .addComponent(jButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChangeDiemCKjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(changeDiemGKjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jButton8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton12)))))
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maHPjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenHPjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maLopjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hocKyjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sTTjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maSVjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenSVjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diemGKjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diemCKjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeDiemGKjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoaSVjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themSVjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangeDiemCKjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dSSVjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dSSVjTableMouseClicked
        // TODO add your handling code here:
        ((ListStudentController)controller).setTextSelectedRow();
    }//GEN-LAST:event_dSSVjTableMouseClicked

    private void dSSVjTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dSSVjTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dSSVjTableKeyPressed

    private void sTTjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sTTjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sTTjTextFieldActionPerformed

    private void maSVjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSVjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maSVjTextFieldActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(new ManageCourseJPanel(controller.getUser()));
        jPanel1.validate();
        jPanel1.repaint();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        ((ListStudentController)controller).setNULL();
        ((ListStudentController)controller).setTextDSSV();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        ((ListStudentController)controller).updateDiem();
        ((ListStudentController)controller).setTextDSSV();
    }//GEN-LAST:event_jButton8MouseClicked

    private void xoaSVjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoaSVjButtonMouseClicked
        ((ListStudentController)controller).deleteSV();
    }//GEN-LAST:event_xoaSVjButtonMouseClicked

    private void themSVjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themSVjButtonMouseClicked
        ((ListStudentController)controller).importSV();
    }//GEN-LAST:event_themSVjButtonMouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        ((ListStudentController)controller).exportSV();
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        ((ListStudentController)controller).updateSV();
    }//GEN-LAST:event_jButton12MouseClicked

    private void themSVjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themSVjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_themSVjButtonActionPerformed

    private void sTTjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sTTjTextFieldKeyReleased
        // TODO add your handling code here:
        ((ListStudentController)controller).sTTFilter();
    }//GEN-LAST:event_sTTjTextFieldKeyReleased

    private void maSVjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maSVjTextFieldKeyReleased
        // TODO add your handling code here:
        ((ListStudentController)controller).maSVFilter();
    }//GEN-LAST:event_maSVjTextFieldKeyReleased

    private void tenSVjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenSVjTextFieldKeyReleased
        // TODO add your handling code here:
        ((ListStudentController)controller).tenHPFilter();
    }//GEN-LAST:event_tenSVjTextFieldKeyReleased

    private void diemGKjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diemGKjTextFieldKeyReleased
        // TODO add your handling code here:
        ((ListStudentController)controller).diemGKFilter();
    }//GEN-LAST:event_diemGKjTextFieldKeyReleased

    private void diemCKjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diemCKjTextFieldKeyReleased
        // TODO add your handling code here:
        ((ListStudentController)controller).diemCKFilter();
    }//GEN-LAST:event_diemCKjTextFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChangeDiemCKjTextField;
    private javax.swing.JTextField changeDiemGKjTextField;
    private javax.swing.JTable dSSVjTable;
    private javax.swing.JTextField diemCKjTextField;
    private javax.swing.JTextField diemGKjTextField;
    private javax.swing.JLabel hocKyjLabel;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maHPjLabel;
    private javax.swing.JLabel maLopjLabel;
    private javax.swing.JTextField maSVjTextField;
    private javax.swing.JTextField sTTjTextField;
    private javax.swing.JLabel tenHPjLabel;
    private javax.swing.JTextField tenSVjTextField;
    private javax.swing.JButton themSVjButton;
    private javax.swing.JButton xoaSVjButton;
    // End of variables declaration//GEN-END:variables
}
