/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlsv.view;

import com.qlsv.controller.ManageAccountController;
import com.qlsv.controller.TextBubbleBorder;
import com.qlsv.models.User;
import java.awt.Color;

/**
 *
 * @author Hiddenpants-H
 */
public class ManageAccount extends CommonJPanel {

    /**
     * Creates new form ManageAccount
     */
    public ManageAccount(User user) {
        initComponents();
        sVjRadioButton.setSelected(true);
        usernamejTextField.setEditable(false);
        passwordjTextField.setEditable(false);
        setController(new ManageAccountController(sVjRadioButton, gVjRadioButton, adminjRadioButton, themTkjButton, deletejButton, resetjButton, usernamejTextField, passwordjTextField, iDjTextField, dacTrungjTextField, dacTrungjLabel, user));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        themTkjButton = new javax.swing.JButton();
        sVjRadioButton = new javax.swing.JRadioButton();
        gVjRadioButton = new javax.swing.JRadioButton();
        adminjRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        iDjTextField = new javax.swing.JTextField();
        deletejButton = new javax.swing.JButton();
        resetjButton = new javax.swing.JButton();
        passwordjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dacTrungjLabel = new javax.swing.JLabel();
        usernamejTextField = new javax.swing.JTextField();
        dacTrungjTextField = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        themTkjButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        themTkjButton.setText("Thêm tài khoản");
        themTkjButton.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        themTkjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themTkjButtonMouseClicked(evt);
            }
        });
        themTkjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themTkjButtonActionPerformed(evt);
            }
        });

        sVjRadioButton.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(sVjRadioButton);
        sVjRadioButton.setText("Sinh viên");
        sVjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sVjRadioButtonActionPerformed(evt);
            }
        });

        gVjRadioButton.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(gVjRadioButton);
        gVjRadioButton.setText("Giảng viên");
        gVjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gVjRadioButtonActionPerformed(evt);
            }
        });

        adminjRadioButton.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(adminjRadioButton);
        adminjRadioButton.setText("Admin");
        adminjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminjRadioButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("ID tài khoản");

        iDjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        iDjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));

        deletejButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        deletejButton.setText("xóa tài khoản");
        deletejButton.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        deletejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletejButtonMouseClicked(evt);
            }
        });
        deletejButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deletejButtonKeyPressed(evt);
            }
        });

        resetjButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        resetjButton.setText("đổi mật khẩu về mặc định");
        resetjButton.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        resetjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetjButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetjButtonMouseEntered(evt);
            }
        });

        passwordjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passwordjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Password");

        dacTrungjLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dacTrungjLabel.setText("Chương Trình or Level");

        usernamejTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usernamejTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));

        dacTrungjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dacTrungjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dacTrungjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(sVjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gVjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(usernamejTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dacTrungjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(themTkjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(312, 312, 312)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deletejButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(iDjTextField)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sVjRadioButton)
                    .addComponent(gVjRadioButton)
                    .addComponent(adminjRadioButton)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(iDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deletejButton)
                            .addComponent(resetjButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dacTrungjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dacTrungjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(themTkjButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void themTkjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themTkjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_themTkjButtonActionPerformed

    private void adminjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminjRadioButtonActionPerformed
        ((ManageAccountController)controller).setVisable(false);
    }//GEN-LAST:event_adminjRadioButtonActionPerformed

    private void gVjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gVjRadioButtonActionPerformed
        ((ManageAccountController)controller).setVisable(true);
        ((ManageAccountController)controller).setView();
    }//GEN-LAST:event_gVjRadioButtonActionPerformed

    private void sVjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sVjRadioButtonActionPerformed
        ((ManageAccountController)controller).setVisable(true);
        ((ManageAccountController)controller).setView();
    }//GEN-LAST:event_sVjRadioButtonActionPerformed

    private void themTkjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themTkjButtonMouseClicked
        ((ManageAccountController)controller).addAccount();
    }//GEN-LAST:event_themTkjButtonMouseClicked

    private void deletejButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deletejButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletejButtonKeyPressed

    private void deletejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletejButtonMouseClicked
        ((ManageAccountController)controller).deleteUser();
    }//GEN-LAST:event_deletejButtonMouseClicked

    private void resetjButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetjButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_resetjButtonMouseEntered

    private void resetjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetjButtonMouseClicked
        ((ManageAccountController)controller).resetPassword();
    }//GEN-LAST:event_resetjButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminjRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dacTrungjLabel;
    private javax.swing.JTextField dacTrungjTextField;
    private javax.swing.JButton deletejButton;
    private javax.swing.JRadioButton gVjRadioButton;
    private javax.swing.JTextField iDjTextField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passwordjTextField;
    private javax.swing.JButton resetjButton;
    private javax.swing.JRadioButton sVjRadioButton;
    private javax.swing.JButton themTkjButton;
    private javax.swing.JTextField usernamejTextField;
    // End of variables declaration//GEN-END:variables
}
