/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlsv.view;

import com.qlsv.controller.QuanLyLopController;
import com.qlsv.controller.TextBubbleBorder;
import com.qlsv.models.Admin;
import com.qlsv.models.GiangVien;
import com.qlsv.models.User;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFileChooser;

/**
 *
 * @author Hiddenpants-H
 */
public class ManageCourseJPanel extends CommonJPanel {

    /**
     * Creates new form ManageCourseJPanel
     */
    public ManageCourseJPanel(User user) {
        initComponents();
        dSLopjTable.getTableHeader().setFont(new Font("Arial",Font.BOLD,12));
        dSLopjTable.getTableHeader().setBackground(new Color(255,102,102));
        dSLopjTable.getTableHeader().setForeground(new Color(255,255,255));
        setController(new QuanLyLopController(dSLopjTable, hocKyjTextField, maHPjTextField, maLopjTextField, maGVjTextField, soSVjTextField, tenHPjTextField, tCjTextField, qTjTextField, jPanel1, xoaLopjButton, themLopjButton, user));
        ((QuanLyLopController)controller).setView();
        ((QuanLyLopController)controller).setTextDSL();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dSLopjTable = new javax.swing.JTable();
        hocKyjTextField = new javax.swing.JTextField();
        maHPjTextField = new javax.swing.JTextField();
        maLopjTextField = new javax.swing.JTextField();
        maGVjTextField = new javax.swing.JTextField();
        soSVjTextField = new javax.swing.JTextField();
        tenHPjTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        themLopjButton = new javax.swing.JButton();
        xoaLopjButton = new javax.swing.JButton();
        tCjTextField = new javax.swing.JTextField();
        qTjTextField = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1067, 768));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Danh sách lớp giảng dạy");

        dSLopjTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dSLopjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Học kỳ", "Tên học phần", "Mã học phần", "Mã lớp", "Tc", "Trọng số", "Mã giảng viên", "Số sinh viên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dSLopjTable.setRowHeight(25);
        dSLopjTable.setSelectionBackground(new java.awt.Color(102, 255, 255));
        dSLopjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dSLopjTableMouseClicked(evt);
            }
        });
        dSLopjTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dSLopjTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(dSLopjTable);
        if (dSLopjTable.getColumnModel().getColumnCount() > 0) {
            dSLopjTable.getColumnModel().getColumn(0).setMinWidth(100);
            dSLopjTable.getColumnModel().getColumn(0).setMaxWidth(100);
            dSLopjTable.getColumnModel().getColumn(4).setMinWidth(100);
            dSLopjTable.getColumnModel().getColumn(4).setMaxWidth(100);
            dSLopjTable.getColumnModel().getColumn(5).setMinWidth(100);
            dSLopjTable.getColumnModel().getColumn(5).setMaxWidth(100);
            dSLopjTable.getColumnModel().getColumn(7).setMinWidth(100);
            dSLopjTable.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        hocKyjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        hocKyjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        hocKyjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hocKyjTextFieldActionPerformed(evt);
            }
        });
        hocKyjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hocKyjTextFieldKeyReleased(evt);
            }
        });

        maHPjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        maHPjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        maHPjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maHPjTextFieldMouseClicked(evt);
            }
        });
        maHPjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maHPjTextFieldActionPerformed(evt);
            }
        });
        maHPjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maHPjTextFieldKeyReleased(evt);
            }
        });

        maLopjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        maLopjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        maLopjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maLopjTextFieldActionPerformed(evt);
            }
        });
        maLopjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maLopjTextFieldKeyReleased(evt);
            }
        });

        maGVjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        maGVjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        maGVjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maGVjTextFieldActionPerformed(evt);
            }
        });
        maGVjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maGVjTextFieldKeyReleased(evt);
            }
        });

        soSVjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        soSVjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        soSVjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soSVjTextFieldActionPerformed(evt);
            }
        });
        soSVjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soSVjTextFieldKeyReleased(evt);
            }
        });

        tenHPjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tenHPjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        tenHPjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tenHPjTextFieldKeyReleased(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Reset");
        jButton3.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("Xem chi tiết");
        jButton4.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        themLopjButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        themLopjButton.setText("Thêm Lớp sv(Excel)");
        themLopjButton.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        themLopjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themLopjButtonMouseClicked(evt);
            }
        });

        xoaLopjButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        xoaLopjButton.setText("Xóa lớp đã chọn");
        xoaLopjButton.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        xoaLopjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoaLopjButtonMouseClicked(evt);
            }
        });

        tCjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tCjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        tCjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCjTextFieldKeyReleased(evt);
            }
        });

        qTjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        qTjTextField.setBorder(new TextBubbleBorder(Color.MAGENTA.darker(), 1, 5, 0));
        qTjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qTjTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(xoaLopjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(themLopjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(hocKyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(279, 279, 279)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tenHPjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(maHPjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(maLopjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tCjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(qTjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(maGVjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(soSVjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maLopjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hocKyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soSVjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maGVjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maHPjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenHPjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qTjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themLopjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoaLopjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1277, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dSLopjTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dSLopjTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dSLopjTableKeyPressed

    private void hocKyjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hocKyjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hocKyjTextFieldActionPerformed

    private void dSLopjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dSLopjTableMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dSLopjTableMouseClicked

    private void maHPjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maHPjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maHPjTextFieldActionPerformed

    private void maLopjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maLopjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maLopjTextFieldActionPerformed

    private void maGVjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maGVjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maGVjTextFieldActionPerformed

    private void soSVjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soSVjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soSVjTextFieldActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        ((QuanLyLopController)controller).setTextDSL();
        ((QuanLyLopController)controller).setNULL();
    }//GEN-LAST:event_jButton3MouseClicked

    private void maHPjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maHPjTextFieldMouseClicked
        
    }//GEN-LAST:event_maHPjTextFieldMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        ((QuanLyLopController)controller).selected();
    }//GEN-LAST:event_jButton4MouseClicked

    private void themLopjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themLopjButtonMouseClicked
        ((QuanLyLopController)controller).addLop();
    }//GEN-LAST:event_themLopjButtonMouseClicked

    private void xoaLopjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoaLopjButtonMouseClicked
        ((QuanLyLopController)controller).deleteLop();
    }//GEN-LAST:event_xoaLopjButtonMouseClicked

    private void hocKyjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hocKyjTextFieldKeyReleased
        // TODO add your handling code here:
        ((QuanLyLopController)controller).hocKyFilter();
    }//GEN-LAST:event_hocKyjTextFieldKeyReleased

    private void tenHPjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenHPjTextFieldKeyReleased
        // TODO add your handling code here:
        ((QuanLyLopController)controller).tenHPFilter();
    }//GEN-LAST:event_tenHPjTextFieldKeyReleased

    private void maHPjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maHPjTextFieldKeyReleased
        // TODO add your handling code here:
        ((QuanLyLopController)controller).maHPFilter();
    }//GEN-LAST:event_maHPjTextFieldKeyReleased

    private void maLopjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maLopjTextFieldKeyReleased
        // TODO add your handling code here:
        ((QuanLyLopController)controller).maLopFilter();
    }//GEN-LAST:event_maLopjTextFieldKeyReleased

    private void tCjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCjTextFieldKeyReleased
        // TODO add your handling code here:
        ((QuanLyLopController)controller).tcFilter();
    }//GEN-LAST:event_tCjTextFieldKeyReleased

    private void qTjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qTjTextFieldKeyReleased
        ((QuanLyLopController)controller).qTFilter();
    }//GEN-LAST:event_qTjTextFieldKeyReleased

    private void maGVjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maGVjTextFieldKeyReleased
        // TODO add your handling code here:
        ((QuanLyLopController)controller).maGVFilter();
    }//GEN-LAST:event_maGVjTextFieldKeyReleased

    private void soSVjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soSVjTextFieldKeyReleased
        // TODO add your handling code here:
        ((QuanLyLopController)controller).soSVFilter();
    }//GEN-LAST:event_soSVjTextFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dSLopjTable;
    private javax.swing.JTextField hocKyjTextField;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maGVjTextField;
    private javax.swing.JTextField maHPjTextField;
    private javax.swing.JTextField maLopjTextField;
    private javax.swing.JTextField qTjTextField;
    private javax.swing.JTextField soSVjTextField;
    private javax.swing.JTextField tCjTextField;
    private javax.swing.JTextField tenHPjTextField;
    private javax.swing.JButton themLopjButton;
    private javax.swing.JButton xoaLopjButton;
    // End of variables declaration//GEN-END:variables
}
