/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlsv.view;

import com.qlsv.controller.HomeController;
import com.qlsv.controller.TextBubbleBorder;
import java.awt.Color;

/**
 *
 * @author Hiddenpants-H
 */
public class TrangChuJPanel extends javax.swing.JPanel {
    private HomeController controller;

    public HomeController getController() {
        return controller;
    }

    public void setController(HomeController controller) {
        this.controller = controller;
    }
    
    /**
     * Creates new form TrangChuJPanel
     */
    public TrangChuJPanel() {
        initComponents();
        controller = new HomeController(count1, count2, count3);
        controller.setCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        KhoaHocJPanel = new javax.swing.JPanel();
        KhoaHocjLabel = new javax.swing.JLabel();
        count2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        KhoaHocJPanel1 = new javax.swing.JPanel();
        KhoaHocjLabel1 = new javax.swing.JLabel();
        count1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        KhoaHocJPanel4 = new javax.swing.JPanel();
        KhoaHocjLabel4 = new javax.swing.JLabel();
        count3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        KhoaHocJPanel.setBackground(new java.awt.Color(0, 204, 204));

        KhoaHocjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlsv/image/icon_ung_dung_48dp.png"))); // NOI18N

        count2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        count2.setForeground(new java.awt.Color(255, 255, 255));
        count2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        count2.setText("100");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sinh Viên");

        jPanel3.setPreferredSize(new java.awt.Dimension(5, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout KhoaHocJPanelLayout = new javax.swing.GroupLayout(KhoaHocJPanel);
        KhoaHocJPanel.setLayout(KhoaHocJPanelLayout);
        KhoaHocJPanelLayout.setHorizontalGroup(
            KhoaHocJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhoaHocJPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(KhoaHocjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(KhoaHocJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KhoaHocJPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57))
                    .addGroup(KhoaHocJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(count2)
                        .addContainerGap())))
        );
        KhoaHocJPanelLayout.setVerticalGroup(
            KhoaHocJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhoaHocJPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(KhoaHocJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KhoaHocJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(KhoaHocJPanelLayout.createSequentialGroup()
                            .addComponent(count2)
                            .addGap(35, 35, 35)
                            .addComponent(jLabel1))
                        .addComponent(KhoaHocjLabel)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        KhoaHocJPanel1.setBackground(new java.awt.Color(255, 102, 102));

        KhoaHocjLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlsv/image/icon_event.png"))); // NOI18N

        count1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        count1.setForeground(new java.awt.Color(255, 255, 255));
        count1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        count1.setText("100");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Khóa Học");

        jPanel2.setPreferredSize(new java.awt.Dimension(5, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout KhoaHocJPanel1Layout = new javax.swing.GroupLayout(KhoaHocJPanel1);
        KhoaHocJPanel1.setLayout(KhoaHocJPanel1Layout);
        KhoaHocJPanel1Layout.setHorizontalGroup(
            KhoaHocJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhoaHocJPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(KhoaHocjLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(KhoaHocJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KhoaHocJPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(count1)
                        .addContainerGap())
                    .addGroup(KhoaHocJPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addContainerGap(46, Short.MAX_VALUE))))
        );
        KhoaHocJPanel1Layout.setVerticalGroup(
            KhoaHocJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhoaHocJPanel1Layout.createSequentialGroup()
                .addGroup(KhoaHocJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KhoaHocJPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(KhoaHocJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KhoaHocjLabel1)
                            .addGroup(KhoaHocJPanel1Layout.createSequentialGroup()
                                .addComponent(count1)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2))))
                    .addGroup(KhoaHocJPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        KhoaHocJPanel4.setBackground(new java.awt.Color(0, 204, 51));

        KhoaHocjLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlsv/image/icon_cap_sach.png"))); // NOI18N

        count3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        count3.setForeground(new java.awt.Color(255, 255, 255));
        count3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        count3.setText("100");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giảng Viên");

        jPanel4.setPreferredSize(new java.awt.Dimension(5, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout KhoaHocJPanel4Layout = new javax.swing.GroupLayout(KhoaHocJPanel4);
        KhoaHocJPanel4.setLayout(KhoaHocJPanel4Layout);
        KhoaHocJPanel4Layout.setHorizontalGroup(
            KhoaHocJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhoaHocJPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(KhoaHocjLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(KhoaHocJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KhoaHocJPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KhoaHocJPanel4Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(count3)
                        .addContainerGap())))
        );
        KhoaHocJPanel4Layout.setVerticalGroup(
            KhoaHocJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhoaHocJPanel4Layout.createSequentialGroup()
                .addGroup(KhoaHocJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KhoaHocJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KhoaHocJPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(count3)
                            .addGap(35, 35, 35)
                            .addComponent(jLabel5))
                        .addGroup(KhoaHocJPanel4Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(KhoaHocjLabel4)))
                    .addGroup(KhoaHocJPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(KhoaHocJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(KhoaHocJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(KhoaHocJPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KhoaHocJPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KhoaHocJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KhoaHocJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(542, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KhoaHocJPanel;
    private javax.swing.JPanel KhoaHocJPanel1;
    private javax.swing.JPanel KhoaHocJPanel4;
    private javax.swing.JLabel KhoaHocjLabel;
    private javax.swing.JLabel KhoaHocjLabel1;
    private javax.swing.JLabel KhoaHocjLabel4;
    private javax.swing.JLabel count1;
    private javax.swing.JLabel count2;
    private javax.swing.JLabel count3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
